# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ibabyair.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
# import socket
# from com.search import host_ip

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(930, 613)
        #设置窗口不允许最大化 Kenny add
        Form.setWindowFlags(QtCore.Qt.MSWindowsFixedSizeDialogHint)
        
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 909, 591))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.deviceCountLabel = QtGui.QLabel(self.widget)
        self.deviceCountLabel.setObjectName(_fromUtf8("deviceCountLabel"))
        self.verticalLayout_2.addWidget(self.deviceCountLabel)
        self.resultListWidget = QtGui.QListWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultListWidget.sizePolicy().hasHeightForWidth())
        self.resultListWidget.setSizePolicy(sizePolicy)
        self.resultListWidget.setMinimumSize(QtCore.QSize(200, 300))
        self.resultListWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout_2.addWidget(self.resultListWidget)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.scanBtn = QtGui.QPushButton(self.widget)
        self.scanBtn.setMinimumSize(QtCore.QSize(80, 50))
        self.scanBtn.setObjectName(_fromUtf8("scanBtn"))
        self.verticalLayout_2.addWidget(self.scanBtn)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.line_2 = QtGui.QFrame(self.widget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_2.addWidget(self.line_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setVerticalSpacing(30)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.brightneSlider = QtGui.QSlider(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightneSlider.sizePolicy().hasHeightForWidth())
        self.brightneSlider.setSizePolicy(sizePolicy)
        self.brightneSlider.setMinimumSize(QtCore.QSize(150, 20))
        self.brightneSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightneSlider.setObjectName(_fromUtf8("brightneSlider"))
        self.gridLayout.addWidget(self.brightneSlider, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.greenSlider = QtGui.QSlider(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenSlider.sizePolicy().hasHeightForWidth())
        self.greenSlider.setSizePolicy(sizePolicy)
        self.greenSlider.setMinimumSize(QtCore.QSize(150, 0))
        self.greenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.greenSlider.setObjectName(_fromUtf8("greenSlider"))
        self.gridLayout.addWidget(self.greenSlider, 2, 1, 1, 1)
        self.redSlider = QtGui.QSlider(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redSlider.sizePolicy().hasHeightForWidth())
        self.redSlider.setSizePolicy(sizePolicy)
        self.redSlider.setMinimumSize(QtCore.QSize(150, 0))
        self.redSlider.setOrientation(QtCore.Qt.Horizontal)
        self.redSlider.setObjectName(_fromUtf8("redSlider"))
        self.gridLayout.addWidget(self.redSlider, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 3, 1, 1)
        self.blueSlider = QtGui.QSlider(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blueSlider.sizePolicy().hasHeightForWidth())
        self.blueSlider.setSizePolicy(sizePolicy)
        self.blueSlider.setMinimumSize(QtCore.QSize(150, 0))
        self.blueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blueSlider.setObjectName(_fromUtf8("blueSlider"))
        self.gridLayout.addWidget(self.blueSlider, 3, 1, 1, 1)
        self.connStutesLabel = QtGui.QLabel(self.widget)
        self.connStutesLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.connStutesLabel.setObjectName(_fromUtf8("connStutesLabel"))
        self.gridLayout.addWidget(self.connStutesLabel, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.TempLabel = QtGui.QLabel(self.widget)
        self.TempLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.TempLabel.setObjectName(_fromUtf8("TempLabel"))
        self.gridLayout.addWidget(self.TempLabel, 1, 4, 1, 1)
        self.wetLabel = QtGui.QLabel(self.widget)
        self.wetLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.wetLabel.setObjectName(_fromUtf8("wetLabel"))
        self.gridLayout.addWidget(self.wetLabel, 2, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.vocLabel = QtGui.QLabel(self.widget)
        self.vocLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.vocLabel.setObjectName(_fromUtf8("vocLabel"))
        self.gridLayout.addWidget(self.vocLabel, 3, 4, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.openLEDBtn = QtGui.QPushButton(self.widget)
        self.openLEDBtn.setCheckable(True)#kenny add
        self.openLEDBtn.setMinimumSize(QtCore.QSize(80, 50))#kenny add
        self.openLEDBtn.setObjectName(_fromUtf8("openLEDBtn"))
        self.horizontalLayout.addWidget(self.openLEDBtn)
        self.listenBtn = QtGui.QPushButton(self.widget)
        self.listenBtn.setCheckable(True)#kenny add
        self.listenBtn.setMinimumSize(QtCore.QSize(80, 50))#kenny add
        self.listenBtn.setObjectName(_fromUtf8("listenBtn"))
        self.horizontalLayout.addWidget(self.listenBtn)
        self.speakBtn = QtGui.QPushButton(self.widget)
        self.speakBtn.setCheckable(True)#kenny add
        self.speakBtn.setMinimumSize(QtCore.QSize(80, 50))#kenny add
        self.speakBtn.setObjectName(_fromUtf8("speakBtn"))
        self.horizontalLayout.addWidget(self.speakBtn)
        self.setBtn = QtGui.QPushButton(self.widget)
        self.setBtn.setCheckable(True)#kenny add
        self.setBtn.setMinimumSize(QtCore.QSize(80, 50))#kenny add
        self.setBtn.setObjectName(_fromUtf8("setBtn"))
        self.horizontalLayout.addWidget(self.setBtn)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem12)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        # host_ip = socket.gethostbyname(socket.gethostname())
#         Form.setWindowTitle(_translate("Form", u"iBaby Air Tools V1.2",None))
#
#         Form.setWindowIcon(QtGui.QIcon("2.PNG"))
# #         self.widget.setWindowIcon(QtGui.QIcon("2.PNG"))

        
        self.deviceCountLabel.setText(_translate("Form", "共搜索到", None))
        self.scanBtn.setText(_translate("Form", "搜索", None))
        self.label_4.setText(_translate("Form", "连接状态：", None))
        self.label.setText(_translate("Form", "温度：", None))
        self.label_6.setText(_translate("Form", "红：", None))
        self.label_7.setText(_translate("Form", "绿：", None))
        self.label_2.setText(_translate("Form", "湿度：", None))
        self.connStutesLabel.setText(_translate("Form", "daff", None))
        self.label_3.setText(_translate("Form", "空气质量：", None))
        self.label_5.setText(_translate("Form", "亮度：", None))
        self.TempLabel.setText(_translate("Form", "fadfa", None))
        self.wetLabel.setText(_translate("Form", "dagag", None))
        self.label_8.setText(_translate("Form", "蓝：", None))
        self.vocLabel.setText(_translate("Form", "gdafw", None))
        self.openLEDBtn.setText(_translate("Form", "打开LED", None))
        self.listenBtn.setText(_translate("Form", "打开监听", None))
        self.speakBtn.setText(_translate("Form", "打开对讲", None))
        self.setBtn.setText(_translate("Form", "设为工装态", None))

